09-28 02:44:22 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
09-28 02:44:22 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
09-28 02:44:24 jdbc[15]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
09-28 02:44:24 jdbc[15]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
09-30 04:58:25 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.<init>(JdbcStatement.java:49)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
09-30 04:58:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
09-30 04:58:25 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.<init>(JdbcStatement.java:49)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-01 00:37:42 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-01 00:37:42 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-03 07:49:42 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-03 07:49:42 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-04 02:05:42 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-04 02:05:42 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-04 02:05:42 jdbc[35]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 02:05:42 jdbc[35]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 15:44:58 jdbc[23]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 15:44:58 jdbc[23]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 15:44:59 jdbc[27]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 15:44:59 jdbc[27]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 15:44:59 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 15:44:59 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 19:24:48 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-04 19:24:48 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-07 04:13:52 jdbc[499]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-07 04:13:52 jdbc[500]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-07 04:13:52 jdbc[499]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-07 04:13:52 jdbc[500]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-07 04:13:52 jdbc[502]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-07 04:13:52 jdbc[506]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-07 04:13:52 jdbc[506]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-07 13:41:37 jdbc[512]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-07 13:41:37 jdbc[511]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-12 07:18:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.<init>(JdbcStatement.java:49)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-12 07:18:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.<init>(JdbcStatement.java:49)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-12 07:18:59 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-12 15:50:02 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-12 15:50:02 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 01:33:52 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 01:33:52 jdbc[34]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 01:33:53 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-17 01:33:53 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-17 01:33:53 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 01:33:53 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 08:40:31 jdbc[43]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-17 08:40:31 jdbc[43]: exception
org.h2.jdbc.JdbcSQLException: Connection is broken: "session closed" [90067-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.engine.Session.prepareLocal(Session.java:420)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
10-17 08:40:31 jdbc[36]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 08:40:31 jdbc[36]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 08:40:33 jdbc[42]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 08:40:33 jdbc[42]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 08:40:33 jdbc[38]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-17 08:40:33 jdbc[38]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-17 15:35:33 jdbc[39]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 15:35:34 jdbc[45]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 15:35:34 jdbc[45]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-17 15:35:35 jdbc[47]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-21 02:26:12 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-21 02:26:13 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-22 23:12:51 jdbc[48]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1443)
	at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:446)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.getAutoCommit(NewProxyConnection.java:938)
	at org.hibernate.c3p0.internal.C3P0ConnectionProvider.getConnection(C3P0ConnectionProvider.java:94)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:67)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:162)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1471)
	at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:356)
	at com.sun.proxy.$Proxy20.beginTransaction(Unknown Source)
	at org.yawlfoundation.yawl.util.HibernateEngine.beginTransaction(HibernateEngine.java:318)
	at org.yawlfoundation.yawl.util.HibernateEngine.getOrBeginTransaction(HibernateEngine.java:213)
	at org.yawlfoundation.yawl.util.HibernateEngine.exec(HibernateEngine.java:153)
	at org.yawlfoundation.yawl.authentication.YSessionCache.audit(YSessionCache.java:253)
	at org.yawlfoundation.yawl.authentication.YSessionCache.shutdown(YSessionCache.java:196)
	at org.yawlfoundation.yawl.engine.YEngine.shutdown(YEngine.java:361)
	at org.yawlfoundation.yawl.engine.interfce.EngineGatewayImpl.shutdown(EngineGatewayImpl.java:249)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EngineBasedServer.destroy(InterfaceB_EngineBasedServer.java:211)
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1486)
	at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1847)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5700)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1590)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1579)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
10-25 00:08:25 jdbc[38]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-25 00:08:25 jdbc[38]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
10-25 00:08:26 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.<init>(JdbcStatement.java:49)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-25 00:08:26 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convert(DbException.java:294)
	at org.h2.message.DbException.toSQLException(DbException.java:267)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:372)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:305)
	at org.h2.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:155)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:197)
	at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:74)
	at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:503)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:463)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:435)
	at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:2151)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.<init>(JdbcStatement.java:49)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareAutoCloseStatement(JdbcConnection.java:301)
	... 9 more
10-25 03:46:30 jdbc[41]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "null"; SQL statement:
INSERT INTO LOANAPPID VALUES ('null','2021-10-25','null','null','null') -- ('null', '2021-10-25', 'null', 'null', 'null') [22007-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.value.ValueDate.parse(ValueDate.java:71)
	at org.h2.value.Value.convertTo(Value.java:860)
	at org.h2.table.Column.convert(Column.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:144)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:132)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:117)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:39)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: null
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:273)
	at org.h2.value.ValueDate.parse(ValueDate.java:69)
	... 13 more
10-25 04:10:16 jdbc[42]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:36)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 14 more
10-25 04:10:16 jdbc[42]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "null"; SQL statement:
INSERT INTO LOANAPPID VALUES ('null','2021-10-25','null','null','null') -- ('null', '2021-10-25', 'null', 'null', 'null') [22007-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.value.ValueDate.parse(ValueDate.java:71)
	at org.h2.value.Value.convertTo(Value.java:860)
	at org.h2.table.Column.convert(Column.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:144)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:132)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:117)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:39)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: null
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:273)
	at org.h2.value.ValueDate.parse(ValueDate.java:69)
	... 13 more
10-25 04:17:21 jdbc[43]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:101)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:36)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:36)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 14 more
10-25 04:21:34 jdbc[44]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "null"; SQL statement:
INSERT INTO LOANAPPID VALUES ('null','2021-10-25','null','null','null') -- ('null', '2021-10-25', 'null', 'null', 'null') [22007-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.value.ValueDate.parse(ValueDate.java:71)
	at org.h2.value.Value.convertTo(Value.java:860)
	at org.h2.table.Column.convert(Column.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:144)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:132)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:117)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:39)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: null
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:273)
	at org.h2.value.ValueDate.parse(ValueDate.java:69)
	... 13 more
10-25 04:27:10 jdbc[45]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:101)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:36)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:131)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:156)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:145)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:200)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1086)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1073)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 16 more
10-25 04:50:30 jdbc[56]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "null"; SQL statement:
INSERT INTO LOANAPPID VALUES ('null','2021-10-25','null','null','null') -- ('null', '2021-10-25', 'null', 'null', 'null') [22007-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.value.ValueDate.parse(ValueDate.java:71)
	at org.h2.value.Value.convertTo(Value.java:860)
	at org.h2.table.Column.convert(Column.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:144)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:132)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:117)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:39)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: null
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:273)
	at org.h2.value.ValueDate.parse(ValueDate.java:69)
	... 13 more
10-25 04:56:49 jdbc[57]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:101)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:36)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.Ifn653.ArchiveLoanApplication.ArchiveLoanApplication.handleEnabledWorkItemEvent(ArchiveLoanApplication.java:36)
	at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedServer$EventHandler.run(InterfaceB_EnvironmentBasedServer.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 14 more
